fix: support events without a payload (#15)
* support events that don't have a payload

For example, 'on: schedule' does not have a payload[1], which results in
an error when attempting to use this action:

    TypeError: Cannot read property 'url' of undefined

This commit updates the code to use the `repo` attribute instead
of parsing out the repo org/name from the repo URL.

1. https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule

* prepare build

```
npm run lint && npm run format && npm run build
```

Added this as a separate commit, as I don't know anything about npm
packages, and it's not clear if all of the package list changes are
desirable.

* README: unify version

It may be preferable to set a v1 link and keep that updated to point to
the latest release.

Also mentioned in PR #11:
https://github.com/CircleCI-Public/trigger-circleci-pipeline-action/pull/11#discussion_r809094800