support events that don't have a payload
For example, 'on: schedule' does not have a payload[1], which results in
an error when attempting to use this action:

    TypeError: Cannot read property 'url' of undefined

This commit updates the code to use the `repo` attribute instead
of parsing out the repo org/name from the repo URL.

1. https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule